### ISSUE TITLE
MKR GSM, connection waiting time

### ISSUE THREAD

**Issue by salvq** [jmpmscorp/Arduino-FreeRTOS-SAMD21-Tickless-Idle#1]
Just more question than issue, does FreeRTOS helping to utilize waiting time for other usefull taks during connection to GSM an/or MQTT broker (using MKRGSM.h and ArduinoMqttClient.h) ?

I am reading DI statuses every change (cca. 15 seconds) and providing data to cloud via GSM/MQTT. However time to time I am getting reconnects to MQTT and/or to GSM so loosing window to read data from digital inputs.

Will this RTOS help me to read data from digital inputs while MKR GSM is being connected to GSM and/or to MQTT ? Currently to connect to GSM takes about 12sec and MQTT about 7sec and main loop is stucked until unit is connected.

Thanks for help

**Comment by jmpmscorp** [comment]
Hi @salvq.

Of course, RTOS will help you. I understand your problem because I have been developing similar project you describe through HTTP instead MQTT. You can think about RTOS like a "multithreading" OS. As you know, while Arduino is waiting a response, CPU is waiting too doing anything. With RTOS, if a task need to wait for a response, scheduler can change "active" task and execute it while other tasks are waiting (inactive). You can read about RTOS in its official website.

In your case, you could have a task monitoring/reconnecting GSM modem. Another task, controlled by GMS task, for example, with notifications, that start/stop MQTT task if GSM is disconnected. And other task, maybe fired with a RTOS timer that execute your measures. You should play with priorities, task stacks, interrupts... to achieve your requirements.

However, I can't help you with official MKRGSM and ArduinoMqttClient libraries because I never used them.

Tell me if I can help you with any other thing.

NOTE: if you want to try FreeRTOS with Arduino, you could start with [https://github.com/BriscoeTech/Arduino-FreeRTOS-SAMD21](url). It's the original port I used. Use my port only if you need Tickless Idle implementation.

**Comment by salvq** [comment]
Thanks for your explanation, sounds really cool...I will go ahead and try this later for sure.
